<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div id="sidebar-bgtop"></div>
		<div id="sidebar-content">
			<ul>				
				<li>
					<h2>Function List:</h2>
					<ul>
						<li><a href="/guestbook.jsp">GuestBook 訪客留言簿</a></li>						
					</ul>
				</li>							
				<li>
					<h2>Online Book Sample:</h2>
					<ul>
						<li><a href="/onlinebook/openGL.jsp">openGL 程序設計指南</a></li>						
					</ul>
				</li>
				<li>
					<h2>我的書架:</h2>
					<ul>
						<li><a href="/books/listBook.jsp">書本清單</a></li>
						<li><a href="/books/insertBook.jsp">新增書本</a></li>
						<!-- 
						<li>修改書本</li>
						<li>刪除書本</li>
						 -->						
					</ul>
				</li>
				<li>
					<h2>Jquery Ex:</h2>
					<ul>
						<li><a href="http://ellenjquery.appspot.com/ui/index.html">Jquery UI EX</a></li>
											
					</ul>
				</li>
				
			</ul>
		</div>
		<div id="sidebar-bgbtm"></div>